services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm-export:/opt/keycloak/data/import
